version: '3'
services:
  scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: scheduler:prod
    environment:
      - NDSCHEDULER_SETTINGS_MODULE=scheduler.settings.production
      - R_LIBS_USER=/R
    restart: unless-stopped
    ports:
      - "8991:8991"
    volumes:
      - /home/ubuntu/code:/root/
      - ~/R/:/R/
