version: '2'
services:
  scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: scheduler:prod
    environment:
      - NDSCHEDULER_SETTINGS_MODULE=scheduler.settings.production
    restart: unless-stopped
    ports:
      - "8991:8991"
    volumes:
      - /home/ubuntu/www/redash-summary:/redash-summary
